# Generated by Django 6.0.4 on 2026-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('sub_admin', 'Project Manager / HOD'), ('user', 'Consultant')], default='user', max_length=20),
        ),
    ]
