# Generated by Django 6.0.4 on 2026-04-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], max_length=10)),
                ('file', models.FileField(upload_to='exports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
