# Generated by Django 6.0.4 on 2026-06-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
        ('reports', '0006_report_assigned_to_project_report_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/%Y/%m/')),
                ('placement', models.CharField(choices=[('cover_only', 'Cover Page Only'), ('every_page', 'Every Page (Page Header)')], default='cover_only', max_length=20)),
                ('width_inches', models.FloatField(default=2.4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='reports.report')),
            ],
        ),
    ]
