# Generated by Django 6.0.4 on 2026-04-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('input_payload', models.JSONField(default=dict)),
                ('prompt_used', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('prompt_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='reports.report')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('agent_type', models.CharField(default='ISO27001Agent', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('evidence_refs', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
