# Generated by Django 6.0.4 on 2026-05-12 10:38

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('standard', 'ISO/IEC Standard'), ('audit_report', 'Audit Report'), ('template', 'Template'), ('soa', 'Statement of Applicability')], default='standard', max_length=30)),
                ('standard_ref', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RAGChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('clause_ref', models.CharField(blank=True, db_index=True, max_length=30)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('theme', models.CharField(blank=True, db_index=True, max_length=50)),
                ('page_start', models.PositiveSmallIntegerField(default=0)),
                ('page_end', models.PositiveSmallIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agents.ragdocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='agents_ragc_documen_cefb38_idx'), models.Index(fields=['theme'], name='agents_ragc_theme_8a0eb2_idx'), models.Index(fields=['clause_ref'], name='agents_ragc_clause__b0e00d_idx')],
            },
        ),
    ]
