/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProcessingIdRouteImport } from './routes/processing.$id'
import { Route as ReportsIdIndexRouteImport } from './routes/reports.$id.index'
import { Route as ReportsIdExportRouteImport } from './routes/reports.$id.export'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProcessingIdRoute = ProcessingIdRouteImport.update({
  id: '/processing/$id',
  path: '/processing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdIndexRoute = ReportsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsIdRoute,
} as any)
const ReportsIdExportRoute = ReportsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/wizard': typeof WizardRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/reports/$id/export': typeof ReportsIdExportRoute
  '/reports/$id/': typeof ReportsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/transparency': typeof TransparencyRoute
  '/wizard': typeof WizardRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/reports/$id/export': typeof ReportsIdExportRoute
  '/reports/$id': typeof ReportsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/wizard': typeof WizardRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/reports/$id/export': typeof ReportsIdExportRoute
  '/reports/$id/': typeof ReportsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/projects'
    | '/transparency'
    | '/wizard'
    | '/processing/$id'
    | '/projects/$id'
    | '/reports/$id'
    | '/projects/'
    | '/reports/$id/export'
    | '/reports/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/transparency'
    | '/wizard'
    | '/processing/$id'
    | '/projects/$id'
    | '/projects'
    | '/reports/$id/export'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/projects'
    | '/transparency'
    | '/wizard'
    | '/processing/$id'
    | '/projects/$id'
    | '/reports/$id'
    | '/projects/'
    | '/reports/$id/export'
    | '/reports/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TransparencyRoute: typeof TransparencyRoute
  WizardRoute: typeof WizardRoute
  ProcessingIdRoute: typeof ProcessingIdRoute
  ReportsIdRoute: typeof ReportsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/processing/$id': {
      id: '/processing/$id'
      path: '/processing/$id'
      fullPath: '/processing/$id'
      preLoaderRoute: typeof ProcessingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id/': {
      id: '/reports/$id/'
      path: '/'
      fullPath: '/reports/$id/'
      preLoaderRoute: typeof ReportsIdIndexRouteImport
      parentRoute: typeof ReportsIdRoute
    }
    '/reports/$id/export': {
      id: '/reports/$id/export'
      path: '/export'
      fullPath: '/reports/$id/export'
      preLoaderRoute: typeof ReportsIdExportRouteImport
      parentRoute: typeof ReportsIdRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReportsIdRouteChildren {
  ReportsIdExportRoute: typeof ReportsIdExportRoute
  ReportsIdIndexRoute: typeof ReportsIdIndexRoute
}

const ReportsIdRouteChildren: ReportsIdRouteChildren = {
  ReportsIdExportRoute: ReportsIdExportRoute,
  ReportsIdIndexRoute: ReportsIdIndexRoute,
}

const ReportsIdRouteWithChildren = ReportsIdRoute._addFileChildren(
  ReportsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  TransparencyRoute: TransparencyRoute,
  WizardRoute: WizardRoute,
  ProcessingIdRoute: ProcessingIdRoute,
  ReportsIdRoute: ReportsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
