/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ProcessingIdRouteImport } from './routes/processing.$id'
import { Route as ReportsIdExportRouteImport } from './routes/reports.$id.export'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AdminRouteImport } from './routes/admin'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingIdRoute = ProcessingIdRouteImport.update({
  id: '/processing/$id',
  path: '/processing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdExportRoute = ReportsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/transparency': typeof TransparencyRoute
  '/wizard': typeof WizardRoute
  '/projects': typeof ProjectsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/reports/$id/export': typeof ReportsIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/transparency': typeof TransparencyRoute
  '/wizard': typeof WizardRoute
  '/projects': typeof ProjectsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/reports/$id/export': typeof ReportsIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/transparency': typeof TransparencyRoute
  '/wizard': typeof WizardRoute
  '/projects': typeof ProjectsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/reports/$id/export': typeof ReportsIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/transparency'
    | '/wizard'
    | '/projects'
    | '/projects/$id'
    | '/admin'
    | '/processing/$id'
    | '/reports/$id'
    | '/reports/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/transparency'
    | '/wizard'
    | '/projects'
    | '/projects/$id'
    | '/admin'
    | '/processing/$id'
    | '/reports/$id'
    | '/reports/$id/export'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/transparency'
    | '/wizard'
    | '/projects'
    | '/projects/$id'
    | '/admin'
    | '/processing/$id'
    | '/reports/$id'
    | '/reports/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TransparencyRoute: typeof TransparencyRoute
  WizardRoute: typeof WizardRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  AdminRoute: typeof AdminRoute
  ProcessingIdRoute: typeof ProcessingIdRoute
  ReportsIdRoute: typeof ReportsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$id': {
      id: '/processing/$id'
      path: '/processing/$id'
      fullPath: '/processing/$id'
      preLoaderRoute: typeof ProcessingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id/export': {
      id: '/reports/$id/export'
      path: '/export'
      fullPath: '/reports/$id/export'
      preLoaderRoute: typeof ReportsIdExportRouteImport
      parentRoute: typeof ReportsIdRoute
    }
  }
}

interface ReportsIdRouteChildren {
  ReportsIdExportRoute: typeof ReportsIdExportRoute
}

const ReportsIdRouteChildren: ReportsIdRouteChildren = {
  ReportsIdExportRoute: ReportsIdExportRoute,
}

const ReportsIdRouteWithChildren = ReportsIdRoute._addFileChildren(
  ReportsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TransparencyRoute: TransparencyRoute,
  WizardRoute: WizardRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  AdminRoute: AdminRoute,
  ProcessingIdRoute: ProcessingIdRoute,
  ReportsIdRoute: ReportsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
