# Generated by Django 6.0.4 on 2026-04-30 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('organisation', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Validation', 'Validation'), ('Scored', 'Scored'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.standard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('original_name', models.CharField(max_length=300)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('type', models.CharField(choices=[('policy', 'Policy'), ('log', 'Log'), ('certificate', 'Certificate'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_score', models.FloatField(default=0)),
                ('evidence_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_GAPS', 'Approved With Gaps'), ('FAILED', 'Failed')], default='FAILED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('action', models.TextField(blank=True)),
                ('expected_evidence', models.TextField(blank=True)),
                ('tag', models.CharField(choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='mandatory', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='reports.clause')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('clause', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='reports.report')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='clause',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='reports.standard'),
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='reports.report')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together={('standard', 'code')},
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partial'), ('non_compliant', 'Non-Compliant')], default='non_compliant', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='reports.report')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.requirement')),
            ],
            options={
                'unique_together': {('report', 'requirement')},
            },
        ),
    ]
