# Generated by Django 6.0.4 on 2026-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rag_context',
            field=models.TextField(blank=True),
        ),
    ]
