# Generated by Django 6.0.4 on 2026-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_rag_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='wizard_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
