# Generated by Django 6.0.4 on 2026-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_wizard_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='service_type',
            field=models.CharField(choices=[('audit_report', 'Internal Audit Report'), ('gap_assessment', 'Gap Assessment Report')], default='audit_report', max_length=20),
        ),
    ]
