# Generated by Django 6.0.4 on 2026-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='rating',
            field=models.CharField(blank=True, choices=[('conformity', 'Conformity'), ('observation', 'Observation'), ('minor_nc', 'Minor Non-Conformity'), ('major_nc', 'Major Non-Conformity'), ('fully_implemented', 'Fully Implemented'), ('partially_implemented', 'Partially Implemented'), ('not_implemented', 'Not Implemented'), ('not_applicable', 'Not Applicable')], default='', max_length=30),
        ),
    ]
