# Generated by Django 6.0.4 on 2026-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_assigned_to_project_report_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Validation', 'Validation'), ('Scored', 'Scored'), ('Completed', 'Completed'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Failed', 'Failed')], default='Draft', max_length=20),
        ),
    ]
